### ISSUE TITLE
merging? master

### ISSUE THREAD

**Issue by gregsyoung** [openskipper/OpenSkipper#3]
hi timo
i know this is a basic question ... but im struggling

I can download openskipper from www.openskipper.org - and it installs and runs ok.
(with the quite old defintions etc)

however if i use the  github repository and download openskipper_master zip file 
it doesnt appear to have an executable file? 

Q: should i somehow merge? these into the openskipper i downloaded?

... what am i missing? where is the application executable file?

**Comment by ttlappalainen** [comment]
Currently binaries has not been included on GitHub. The executables under openskipper.org are the most latest. There is much changes for those. From GitHyb you can take e.g. PgnDefns.N2kdfn.xml and copy it to same path, where you executable is located. Then it will use that.

**Comment by gregsyoung** [comment]
thanks for help... there are some other files in your sample definitions 
q: should i also copy these to the application directory?

**Comment by ttlappalainen** [comment]
- Streams.xml and Connectors.xml are specifig to your environment. They define input ports etc. 

- Parameters.N2kParams.xml defines your data. The sample works in many cases, but you may need change definitions. E.g. NMEA2000 tanks can have different instance values etc. Currently there is only possible to lock some data to NMEA2000 source number. This is not totally correct, since due to address claimin NMEA2000 devices may change they source, when you add new device. Right way would be to lock it to the "CAN NAME".

- Display*.xml files defines how your GUI looks like. I have made samples to get started. You need to study a bit about those definition files and how to configure your own displays. There is no GUI system for moving, adding or deleting controls.

- www directory contains web page definition, if you enable web server. This is also something you can build totally for your own. The sample is good start.
